<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Stock Report PDF</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th, td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        thead {
            background-color: #f2f2f2;
        }

        tfoot {
            background-color: #ffe599;
            font-weight: bold;
        }
    </style>
</head>
<body>

    <h2>📦 Stock Report</h2>
    <p><strong>Generated By:</strong> {{ $user->name }}</p>
    <p><strong>Date:</strong> {{ now()->format('d M Y, h:i A') }}</p>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Item Name</th>
                <th>Category</th>
                <th>Vendor</th>
                <th>Qty</th>
                <th>Amount</th>
                <th>Created By</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($stocks as $index => $s)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $s->item_name }}</td>
                    <td>{{ $s->category->name ?? '-' }}</td>
                    <td>{{ $s->vendor_name }}</td>
                    <td>{{ $s->quantity }}</td>
                    <td>₹{{ number_format($s->amount, 2) }}</td>
                    <td>{{ $s->creator->name ?? 'System' }}</td>
                    <td>{{ $s->created_at->format('d-m-Y') }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">Total Items: {{ $stocks->count() }}</td>
                <td>{{ $stocks->sum('quantity') }}</td>
                <td>₹{{ number_format($stocks->sum('amount'), 2) }}</td>
                <td colspan="2"></td>
                {{-- <td colspan="2">Grand Total: ₹{{ number_format($stocks->sum(fn($s) => $s->quantity * $s->amount), 2) }}</td> --}}
            </tr>
        </tfoot>
    </table>

</body>
</html>
