<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Purchase Requests Export</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #999;
            padding: 6px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        tfoot tr {
            background-color: #fff3cd;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h4 class="mb-3">Purchase Requests Export</h4>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Item Name</th>
                <th>Category</th>
                <th>Quantity</th>
                <th>Requested By</th>
                <th>Department</th>
                <th>Status</th>
                <th>Request Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($requests as $index => $request)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $request->item_name }}</td>
                    <td>{{ $request->category->name ?? '-' }}</td>
                    <td>{{ $request->quantity }}</td>
                    <td>{{ $request->requested_by ?? '-' }}</td>
                    <td>{{ $request->department ?? '-' }}</td>
                    <td>{{ ucfirst($request->status) }}</td>
                    <td>{{ $request->request_date ? \Carbon\Carbon::parse($request->request_date)->format('d-m-Y') : '-' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" class="text-center">No records found.</td>
                </tr>
            @endforelse
        </tbody>
        @if($requests->count() > 0)
            <tfoot>
                <tr>
                    <td colspan="2">Total Items</td>
                    <td colspan="6">{{ $totalItems }}</td>
                </tr>
                <tr>
                    <td colspan="2">Total Quantity</td>
                    <td colspan="6">{{ $totalQuantity }}</td>
                </tr>
            </tfoot>
        @endif
    </table>

    <p class="mt-3">
        <strong>Generated by:</strong> {{ $generatedBy }}
    </p>
</body>
</html>
